-- Versão: 1.0 | Data: 15/07/2026
-- Fase 14: vínculo dos mocks de Data Reunião com o responsável do usuário.
-- As Fases 12/13 (0051/0053) casaram o responsible_id dos mocks por nome
-- pegando a linha MAIS ANTIGA de responsibles com aquele display_name — que
-- pode ser uma duplicata sem vínculo de usuário (responsibles.user_id null).
-- Como o RLS de records (0037) libera a linha pelo vínculo vivo
-- responsibles.user_id = auth.uid(), o vendedor não via os próprios mocks
-- (só admin/gestor, via view_all_records) — e o campo calculado que conta
-- Data Reunião zerava para ele.
-- Este script recalcula o match para TODOS os mocks a partir dos pares
-- (source_id, responsavel) originais das Fases 12/13 (o nome não fica
-- persistido no record), agora preferindo a linha de responsibles vinculada a
-- usuário; empate segue resolvendo pela mais antiga (comportamento anterior
-- preservado quando não há vínculo). Também recupera mocks cujo nome não
-- casava na época e passou a existir em responsibles depois.
-- O trigger enforce_reuniao_freeze (0051) não bloqueia UPDATE de
-- responsible_id — nenhum bypass é necessário. Idempotente/determinístico.
-- Snapshots congelam responsible_id: dar refresh nos snapshots depois.

with dados (source_id, responsavel) as (
  values
    ('mock_reuniao_001', 'Gabriella Salles'),
    ('mock_reuniao_002', 'Gabriella Salles'),
    ('mock_reuniao_003', 'Paulo Vitor Santos'),
    ('mock_reuniao_004', 'Gabriella Salles'),
    ('mock_reuniao_005', 'Paulo Vitor Santos'),
    ('mock_reuniao_006', 'Paulo Vitor Santos'),
    ('mock_reuniao_007', 'Gabriella Salles'),
    ('mock_reuniao_008', 'Gabriella Salles'),
    ('mock_reuniao_009', 'Paulo Vitor Santos'),
    ('mock_reuniao_010', 'Paulo Vitor Santos'),
    ('mock_reuniao_011', 'Gabriella Salles'),
    ('mock_reuniao_012', 'Paulo Vitor Santos'),
    ('mock_reuniao_013', 'Gabriella Salles'),
    ('mock_reuniao_014', 'Paulo Vitor Santos'),
    ('mock_reuniao_015', 'Paulo Vitor Santos'),
    ('mock_reuniao_016', 'Paulo Vitor Santos'),
    ('mock_reuniao_017', 'Gabriella Salles'),
    ('mock_reuniao_018', 'Paulo Vitor Santos'),
    ('mock_reuniao_019', 'Paulo Vitor Santos'),
    ('mock_reuniao_020', 'Paulo Vitor Santos'),
    ('mock_reuniao_021', 'Gabriella Salles'),
    ('mock_reuniao_022', 'Paulo Vitor Santos'),
    ('mock_reuniao_023', 'Gabriella Salles'),
    ('mock_reuniao_024', 'Gabriella Salles'),
    ('mock_reuniao_025', 'Paulo Vitor Santos'),
    ('mock_reuniao_026', 'Gabriella Salles'),
    ('mock_reuniao_027', 'Gabriella Salles'),
    ('mock_reuniao_028', 'Paulo Vitor Santos'),
    ('mock_reuniao_029', 'Paulo Vitor Santos'),
    ('mock_reuniao_030', 'Paulo Vitor Santos'),
    ('mock_reuniao_031', 'Gabriella Salles'),
    ('mock_reuniao_032', 'Paulo Vitor Santos'),
    ('mock_reuniao_033', 'Gabriella Salles'),
    ('mock_reuniao_034', 'Paulo Vitor Santos'),
    ('mock_reuniao_035', 'Gabriella Salles'),
    ('mock_reuniao_036', 'Paulo Vitor Santos'),
    ('mock_reuniao_037', 'Paulo Vitor Santos'),
    ('mock_reuniao_038', 'Gabriella Salles'),
    ('mock_reuniao_039', 'Paulo Vitor Santos'),
    ('mock_reuniao_040', 'Paulo Vitor Santos'),
    ('mock_reuniao_041', 'Gabriella Salles'),
    ('mock_reuniao_042', 'Gabriella Salles'),
    ('mock_reuniao_043', 'Gabriella Salles'),
    ('mock_reuniao_044', 'Paulo Vitor Santos'),
    ('mock_reuniao_045', 'Gabriella Salles'),
    ('mock_reuniao_046', 'Paulo Vitor Santos'),
    ('mock_reuniao_047', 'Gabriella Salles'),
    ('mock_reuniao_048', 'Paulo Vitor Santos'),
    ('mock_reuniao_049', 'Gabriella Salles'),
    ('mock_reuniao_050', 'Paulo Vitor Santos'),
    ('mock_reuniao_051', 'Felipe Machado'),
    ('mock_reuniao_052', 'Gabriella Salles'),
    ('mock_reuniao_053', 'Gabriella Salles'),
    ('mock_reuniao_054', 'Gabriella Salles'),
    ('mock_reuniao_055', 'Felipe Machado'),
    ('mock_reuniao_056', 'Felipe Machado'),
    ('mock_reuniao_057', 'Gabriella Salles'),
    ('mock_reuniao_058', 'Gabriella Salles'),
    ('mock_reuniao_059', 'Gabriella Salles'),
    ('mock_reuniao_060', 'Gabriella Salles'),
    ('mock_reuniao_061', 'Gabriella Salles'),
    ('mock_reuniao_062', 'Gabriella Salles'),
    ('mock_reuniao_063', 'Gabriella Salles'),
    ('mock_reuniao_064', 'Gabriella Salles'),
    ('mock_reuniao_065', 'Gabriella Salles'),
    ('mock_reuniao_066', 'Gabriella Salles'),
    ('mock_reuniao_067', 'Gabriella Salles'),
    ('mock_reuniao_068', 'Gabriella Salles'),
    ('mock_reuniao_069', 'Gabriella Salles'),
    ('mock_reuniao_070', 'Gabriella Salles'),
    ('mock_reuniao_071', 'Gabriella Salles'),
    ('mock_reuniao_072', 'Gabriella Salles'),
    ('mock_reuniao_073', 'Felipe Machado'),
    ('mock_reuniao_074', 'Felipe Machado'),
    ('mock_reuniao_075', 'Felipe Machado'),
    ('mock_reuniao_076', 'Felipe Machado'),
    ('mock_reuniao_077', 'Felipe Machado'),
    ('mock_reuniao_078', 'Felipe Machado'),
    ('mock_reuniao_079', 'Felipe Machado'),
    ('mock_reuniao_080', 'Felipe Machado'),
    ('mock_reuniao_081', 'Felipe Machado'),
    ('mock_reuniao_082', 'Felipe Machado'),
    ('mock_reuniao_083', 'Felipe Machado'),
    ('mock_reuniao_084', 'Felipe Machado'),
    ('mock_reuniao_085', 'Felipe Machado'),
    ('mock_reuniao_086', 'Felipe Machado'),
    ('mock_reuniao_087', 'Felipe Machado'),
    ('mock_reuniao_088', 'Felipe Machado'),
    ('mock_reuniao_089', 'Felipe Machado'),
    ('mock_reuniao_090', 'Felipe Machado'),
    ('mock_reuniao_091', 'Felipe Machado'),
    ('mock_reuniao_092', 'Felipe Machado'),
    ('mock_reuniao_093', 'Felipe Machado'),
    ('mock_reuniao_094', 'Gabriella Salles'),
    ('mock_reuniao_095', 'Gabriella Salles'),
    ('mock_reuniao_096', 'Gabriella Salles'),
    ('mock_reuniao_097', 'Gabriella Salles'),
    ('mock_reuniao_098', 'Gabriella Salles'),
    ('mock_reuniao_099', 'Gabriella Salles'),
    ('mock_reuniao_100', 'Gabriella Salles'),
    ('mock_reuniao_101', 'Gabriella Salles'),
    ('mock_reuniao_102', 'Gabriella Salles'),
    ('mock_reuniao_103', 'Gabriella Salles'),
    ('mock_reuniao_104', 'Gabriella Salles'),
    ('mock_reuniao_105', 'Gabriella Salles'),
    ('mock_reuniao_106', 'Gabriella Salles'),
    ('mock_reuniao_107', 'Gabriella Salles'),
    ('mock_reuniao_108', 'Gabriella Salles'),
    ('mock_reuniao_109', 'Gabriella Salles'),
    ('mock_reuniao_110', 'Gabriella Salles'),
    ('mock_reuniao_111', 'Gabriella Salles'),
    ('mock_reuniao_112', 'Gabriella Salles'),
    ('mock_reuniao_113', 'Gabriella Salles'),
    ('mock_reuniao_114', 'Gabriella Salles'),
    ('mock_reuniao_115', 'Gabriella Salles'),
    ('mock_reuniao_116', 'Gabriella Salles'),
    ('mock_reuniao_117', 'Gabriella Salles'),
    ('mock_reuniao_118', 'Gabriella Salles'),
    ('mock_reuniao_119', 'Gabriella Salles'),
    ('mock_reuniao_120', 'Gabriella Salles'),
    ('mock_reuniao_121', 'Gabriella Salles'),
    ('mock_reuniao_122', 'Gabriella Salles'),
    ('mock_reuniao_123', 'Gabriella Salles'),
    ('mock_reuniao_124', 'Gabriella Salles'),
    ('mock_reuniao_125', 'Gabriella Salles'),
    ('mock_reuniao_126', 'Gabriella Salles'),
    ('mock_reuniao_127', 'Paulo Vitor Santos'),
    ('mock_reuniao_128', 'Gabriella Salles'),
    ('mock_reuniao_129', 'Gabriella Salles'),
    ('mock_reuniao_130', 'Gabriella Salles'),
    ('mock_reuniao_131', 'Gabriella Salles'),
    ('mock_reuniao_132', 'Gabriella Salles'),
    ('mock_reuniao_133', 'Gabriella Salles'),
    ('mock_reuniao_134', 'Gabriella Salles'),
    ('mock_reuniao_135', 'Gabriella Salles'),
    ('mock_reuniao_136', 'Gabriella Salles'),
    ('mock_reuniao_137', 'Gabriella Salles'),
    ('mock_reuniao_138', 'Felipe Machado'),
    ('mock_reuniao_139', 'Gabriella Salles'),
    ('mock_reuniao_140', 'Gabriella Salles'),
    ('mock_reuniao_141', 'Gabriella Salles'),
    ('mock_reuniao_142', 'Gabriella Salles'),
    ('mock_reuniao_143', 'Gabriella Salles'),
    ('mock_reuniao_144', 'Gabriella Salles'),
    ('mock_reuniao_145', 'Gabriella Salles'),
    ('mock_reuniao_146', 'Gabriella Salles'),
    ('mock_reuniao_147', 'Gabriella Salles'),
    ('mock_reuniao_148', 'Gabriella Salles'),
    ('mock_reuniao_149', 'Gabriella Salles'),
    ('mock_reuniao_150', 'Gabriella Salles'),
    ('mock_reuniao_151', 'Gabriella Salles'),
    ('mock_reuniao_152', 'Gabriella Salles'),
    ('mock_reuniao_153', 'Gabriella Salles'),
    ('mock_reuniao_154', 'Felipe Machado'),
    ('mock_reuniao_155', 'Gabriella Salles'),
    ('mock_reuniao_156', 'Gabriella Salles'),
    ('mock_reuniao_157', 'Gabriella Salles'),
    ('mock_reuniao_158', 'Gabriella Salles'),
    ('mock_reuniao_159', 'Gabriella Salles'),
    ('mock_reuniao_160', 'Gabriella Salles'),
    ('mock_reuniao_161', 'Gabriella Salles'),
    ('mock_reuniao_162', 'Gabriella Salles'),
    ('mock_reuniao_163', 'Gabriella Salles'),
    ('mock_reuniao_164', 'Gabriella Salles'),
    ('mock_reuniao_165', 'Gabriella Salles'),
    ('mock_reuniao_166', 'Gabriella Salles'),
    ('mock_reuniao_167', 'Gabriella Salles'),
    ('mock_reuniao_168', 'Gabriella Salles'),
    ('mock_reuniao_169', 'Gabriella Salles'),
    ('mock_reuniao_170', 'Gabriella Salles'),
    ('mock_reuniao_171', 'Gabriella Salles'),
    ('mock_reuniao_172', 'Gabriella Salles'),
    ('mock_reuniao_173', 'Gabriella Salles'),
    ('mock_reuniao_174', 'Gabriella Salles'),
    ('mock_reuniao_175', 'Gabriella Salles'),
    ('mock_reuniao_176', 'Gabriella Salles'),
    ('mock_reuniao_177', 'Gabriella Salles'),
    ('mock_reuniao_178', 'Gabriella Salles'),
    ('mock_reuniao_179', 'Gabriella Salles'),
    ('mock_reuniao_180', 'Gabriella Salles'),
    ('mock_reuniao_181', 'Gabriella Salles'),
    ('mock_reuniao_182', 'Gabriella Salles'),
    ('mock_reuniao_183', 'Gabriella Salles'),
    ('mock_reuniao_184', 'Paulo Vitor Santos'),
    ('mock_reuniao_185', 'Paulo Vitor Santos'),
    ('mock_reuniao_186', 'Gabriella Salles'),
    ('mock_reuniao_187', 'Gabriella Salles'),
    ('mock_reuniao_188', 'Gabriella Salles'),
    ('mock_reuniao_189', 'Gabriella Salles'),
    ('mock_reuniao_190', 'Gabriella Salles'),
    ('mock_reuniao_191', 'Gabriella Salles'),
    ('mock_reuniao_192', 'Gabriella Salles'),
    ('mock_reuniao_193', 'Gabriella Salles'),
    ('mock_reuniao_194', 'Gabriella Salles'),
    ('mock_reuniao_195', 'Gabriella Salles'),
    ('mock_reuniao_196', 'Gabriella Salles'),
    ('mock_reuniao_197', 'Gabriella Salles'),
    ('mock_reuniao_198', 'Gabriella Salles'),
    ('mock_reuniao_199', 'Gabriella Salles'),
    ('mock_reuniao_200', 'Gabriella Salles'),
    ('mock_reuniao_201', 'Gabriella Salles'),
    ('mock_reuniao_202', 'Gabriella Salles'),
    ('mock_reuniao_203', 'Gabriella Salles'),
    ('mock_reuniao_204', 'Gabriella Salles'),
    ('mock_reuniao_205', 'Gabriella Salles'),
    ('mock_reuniao_206', 'Gabriella Salles'),
    ('mock_reuniao_207', 'Gabriella Salles'),
    ('mock_reuniao_208', 'Gabriella Salles'),
    ('mock_reuniao_209', 'Gabriella Salles'),
    ('mock_reuniao_210', 'Gabriella Salles'),
    ('mock_reuniao_211', 'Gabriella Salles'),
    ('mock_reuniao_212', 'Gabriella Salles'),
    ('mock_reuniao_213', 'Gabriella Salles'),
    ('mock_reuniao_214', 'Gabriella Salles'),
    ('mock_reuniao_215', 'Gabriella Salles'),
    ('mock_reuniao_216', 'Gabriella Salles'),
    ('mock_reuniao_217', 'Gabriella Salles'),
    ('mock_reuniao_218', 'Gabriella Salles'),
    ('mock_reuniao_219', 'Gabriella Salles'),
    ('mock_reuniao_220', 'Gabriella Salles'),
    ('mock_reuniao_221', 'Gabriella Salles'),
    ('mock_reuniao_222', 'Gabriella Salles'),
    ('mock_reuniao_223', 'Gabriella Salles'),
    ('mock_reuniao_224', 'Gabriella Salles'),
    ('mock_reuniao_225', 'Gabriella Salles'),
    ('mock_reuniao_226', 'Gabriella Salles'),
    ('mock_reuniao_227', 'Gabriella Salles'),
    ('mock_reuniao_228', 'Gabriella Salles'),
    ('mock_reuniao_229', 'Gabriella Salles'),
    ('mock_reuniao_230', 'Gabriella Salles'),
    ('mock_reuniao_231', 'Gabriella Salles'),
    ('mock_reuniao_232', 'Gabriella Salles'),
    ('mock_reuniao_233', 'Gabriella Salles'),
    ('mock_reuniao_234', 'Gabriella Salles'),
    ('mock_reuniao_235', 'Gabriella Salles'),
    ('mock_reuniao_236', 'Gabriella Salles'),
    ('mock_reuniao_237', 'Gabriella Salles'),
    ('mock_reuniao_238', 'Gabriella Salles'),
    ('mock_reuniao_239', 'Gabriella Salles'),
    ('mock_reuniao_240', 'Gabriella Salles'),
    ('mock_reuniao_241', 'Gabriella Salles'),
    ('mock_reuniao_242', 'Gabriella Salles'),
    ('mock_reuniao_243', 'Gabriella Salles'),
    ('mock_reuniao_244', 'Gabriella Salles'),
    ('mock_reuniao_245', 'Gabriella Salles'),
    ('mock_reuniao_246', 'Gabriella Salles'),
    ('mock_reuniao_247', 'Gabriella Salles'),
    ('mock_reuniao_248', 'Gabriella Salles'),
    ('mock_reuniao_249', 'Gabriella Salles'),
    ('mock_reuniao_250', 'Gabriella Salles'),
    ('mock_reuniao_251', 'Gabriella Salles'),
    ('mock_reuniao_252', 'Gabriella Salles'),
    ('mock_reuniao_253', 'Gabriella Salles'),
    ('mock_reuniao_254', 'Gabriella Salles'),
    ('mock_reuniao_255', 'Gabriella Salles'),
    ('mock_reuniao_256', 'Gabriella Salles'),
    ('mock_reuniao_257', 'Gabriella Salles'),
    ('mock_reuniao_258', 'Gabriella Salles'),
    ('mock_reuniao_259', 'Gabriella Salles'),
    ('mock_reuniao_260', 'Gabriella Salles'),
    ('mock_reuniao_261', 'Gabriella Salles'),
    ('mock_reuniao_262', 'Gabriella Salles'),
    ('mock_reuniao_263', 'Gabriella Salles'),
    ('mock_reuniao_264', 'Gabriella Salles'),
    ('mock_reuniao_265', 'Gabriella Salles'),
    ('mock_reuniao_266', 'Gabriella Salles'),
    ('mock_reuniao_267', 'Gabriella Salles'),
    ('mock_reuniao_268', 'Gabriella Salles'),
    ('mock_reuniao_269', 'Gabriella Salles'),
    ('mock_reuniao_270', 'Gabriella Salles'),
    ('mock_reuniao_out_001', 'Gabriella Salles'),
    ('mock_reuniao_out_002', 'Gabriella Salles'),
    ('mock_reuniao_out_003', 'Paulo Vitor Santos'),
    ('mock_reuniao_out_004', 'Paulo Vitor Santos'),
    ('mock_reuniao_out_005', 'Gabriella Salles'),
    ('mock_reuniao_out_006', 'Paulo Vitor Santos'),
    ('mock_reuniao_out_007', 'Paulo Vitor Santos'),
    ('mock_reuniao_out_008', 'Paulo Vitor Santos'),
    ('mock_reuniao_out_009', 'Paulo Vitor Santos'),
    ('mock_reuniao_out_010', 'Gabriella Salles'),
    ('mock_reuniao_out_011', 'Gabriella Salles'),
    ('mock_reuniao_out_012', 'Gabriella Salles'),
    ('mock_reuniao_out_013', 'Felipe Machado'),
    ('mock_reuniao_out_014', 'Felipe Machado'),
    ('mock_reuniao_out_015', 'Felipe Machado'),
    ('mock_reuniao_out_016', 'Felipe Machado'),
    ('mock_reuniao_out_017', 'Felipe Machado'),
    ('mock_reuniao_out_018', 'Felipe Machado'),
    ('mock_reuniao_out_019', 'Felipe Machado'),
    ('mock_reuniao_out_020', 'Gabriella Salles'),
    ('mock_reuniao_out_021', 'Gabriella Salles'),
    ('mock_reuniao_out_022', 'Gabriella Salles'),
    ('mock_reuniao_out_023', 'Gabriella Salles'),
    ('mock_reuniao_out_024', 'Gabriella Salles'),
    ('mock_reuniao_out_025', 'Gabriella Salles'),
    ('mock_reuniao_out_026', 'Gabriella Salles'),
    ('mock_reuniao_out_027', 'Gabriella Salles'),
    ('mock_reuniao_out_028', 'Gabriella Salles'),
    ('mock_reuniao_out_029', 'Gabriella Salles'),
    ('mock_reuniao_out_030', 'Gabriella Salles'),
    ('mock_reuniao_out_031', 'Gabriella Salles'),
    ('mock_reuniao_out_032', 'Gabriella Salles')
),
-- distinct on: nomes duplicados em responsibles não podem multiplicar linhas;
-- (user_id is null) ordena as vinculadas primeiro (false < true).
resp as (
  select distinct on (display_name) id, display_name
  from public.responsibles
  order by display_name, (user_id is null), created_at
)
update public.records r
set responsible_id = resp.id
from dados d
join resp on resp.display_name = d.responsavel
where r.is_mock
  and r.source_system = 'manual'
  and r.source_id = d.source_id
  and r.responsible_id is distinct from resp.id;
